name: Deploy to Production (App Store/Play Store)

on:
  # Trigger on production version tags (e.g., v1.8.0, v1.8.1)
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  
  # Allow manual triggering from GitHub UI
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to deploy (ios, android, all)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ios
          - android

jobs:
  verify-staging:
    name: Verify Staging Deployment
    runs-on: ubuntu-latest
    outputs:
      staging-passed: ${{ steps.check.outputs.passed }}
    
    steps:
      - name: Check if staging deployment passed for this commit
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.sha;
            console.log(`Checking for successful staging deployment of commit: ${sha}`);
            
            // Get workflow runs for the staging workflow
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy-staging.yml',
              status: 'success',
              per_page: 100
            });
            
            // Check if any successful run matches this commit
            const stagingRun = runs.workflow_runs.find(run => run.head_sha === sha);
            
            if (stagingRun) {
              console.log(`✅ Found successful staging deployment: ${stagingRun.html_url}`);
              console.log(`   Run ID: ${stagingRun.id}`);
              console.log(`   Conclusion: ${stagingRun.conclusion}`);
              core.setOutput('passed', 'true');
              return true;
            } else {
              console.log(`❌ No successful staging deployment found for commit ${sha}`);
              console.log(`   This commit must be deployed to staging before production.`);
              core.setOutput('passed', 'false');
              
              // Only fail if not manually triggered with override
              if (context.eventName !== 'workflow_dispatch') {
                core.setFailed('Staging deployment required before production deployment');
              }
              return false;
            }
      
      - name: Staging verification result
        run: |
          if [ "${{ steps.check.outputs.passed }}" = "true" ]; then
            echo "✅ Staging verification passed - proceeding with production deployment"
          else
            echo "⚠️  No staging deployment found for this commit"
            if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
              echo "⚠️  Manual trigger detected - allowing deployment to proceed"
              echo "⚠️  WARNING: This bypasses the staging requirement!"
            else
              echo "❌ Production deployment blocked - deploy to staging first"
              exit 1
            fi
          fi

  deploy-production:
    name: Deploy to Production
    needs: verify-staging
    if: needs.verify-staging.outputs.staging-passed == 'true' || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/build-and-submit.yml
    with:
      profile: 'production'
      platform: ${{ github.event.inputs.platform || 'all' }}
      environment: 'production'
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

