name: Update Dependencies Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 22
    - run: npx npm-check-updates -u
    - run: yarn install
    - uses: actions-js/push@v1.2
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        author_email: jbuxofplenty@gmail.com
        author_name: jbuxofplenty
        message: Updated Dependencies
      
  
