name: Update Dependencies Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    
    - name: Update dependencies
      run: |
        npx npm-check-updates -u
        yarn install
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(deps): update dependencies'
        title: 'chore(deps): automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR updates dependencies to their latest versions using `npm-check-updates`.
          
          Please review the changes and run tests before merging.
          
          ---
          *Auto-generated by GitHub Actions*
        branch: automated-dependency-updates
        delete-branch: true
        labels: dependencies
